# The time will be synced in these worlds, if they are normal ones (not Nether or End ones).
worlds:
  - world

# Sync moon phases?
syncMoonPhases: true

# TimeZone? If invalid, GMT.
timezone: "Europe/Paris"
